"""adds description to polls

Revision ID: 1cdcf0588329
Revises: 1ec01884f10b
Create Date: 2019-05-11 11:50:26.578434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdcf0588329'
down_revision = '1ec01884f10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('description', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'description')
    # ### end Alembic commands ###
