"""empty message

Revision ID: fdfed72f820d
Revises: 28c7908fe9d6
Create Date: 2019-05-07 18:39:15.886264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfed72f820d'
down_revision = '28c7908fe9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.DateTime(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_value'), 'responses', ['value'], unique=False)
    op.add_column('votes', sa.Column('response_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'votes', 'responses', ['response_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'response_id')
    op.drop_index(op.f('ix_responses_value'), table_name='responses')
    op.drop_table('responses')
    # ### end Alembic commands ###
